version: "3.0"

services:
  predict-app:
    image: iris-predictapp
    ports:
      - "5000:5000"
  web-app:
    image: iris-webapp
    depends_on:
      - predict-app
    environment:
      - FLASK_ENDPOINT=http://predict-app:5000/predict  
    ports:
      - "3000:3000"