version: "3.0"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
  mqtt_bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER_ADDRESS=${MQTT_BROKER_ADDRESS}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - TOPIC=${TOPIC}
      - THINGSPEAK_API_KEY=${THINGSPEAK_API_KEY}